#!/usr/bin/env python3

import logging
import os
import subprocess
import sys
import yaml


logger = logging.getLogger(__name__)


def is_focused(my_title):
    logger.debug("Checking focused windows is %s", my_title)
    child = subprocess.run(
        ['xdotool', 'getwindowfocus'],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if child.returncode != 0:
        logger.debug("No focused window found")
        return False
    focused_window = child.stdout.decode('utf-8').strip()

    child = subprocess.run(
        ['xdotool', 'getwindowname', focused_window],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if child.returncode != 0:
        logger.debug("Focused window title not found")
        return False
    focused_title = child.stdout.decode('utf-8').strip()

    logger.debug("Focused windows is %s %r", focused_window, focused_title)

    return my_title in focused_title


logging.basicConfig(
    level=logging.DEBUG if os.environ.get('DEBUG') else logging.INFO,
)

try:
    environ = yaml.load(sys.argv[1])
except IndexError:
    environ = {}

sys.exit(0 if is_focused(os.environ.get('NOTIFY_TITLE')) else 1)
