#!/usr/bin/env python3

import asyncio
from distutils.spawn import find_executable
import os
import logging
import json


logger = logging.getLogger('notify-proxy')
notify_send_path = find_executable('notify-send')


@asyncio.coroutine
def is_focused(window_title):
    logger.debug("Checking focused window for title %s.", window_title)
    child = yield from asyncio.create_subprocess_exec(
        'xdotool', 'getactivewindow', 'getwindowname',
        stdout=asyncio.subprocess.PIPE,
    )
    stdout, _ = yield from child.communicate()
    focused_name = stdout.strip().decode('utf-8')

    return focused_name.endswith(window_title)


@asyncio.coroutine
def window_exists(window_title):
    escaped_title = (
        window_title
        .replace('(', r'\(')
        .replace(')', r'\)')
        .replace('.', r'\.')
    )
    logger.debug("Checking if window %s still exists.", window_title)
    child = yield from asyncio.create_subprocess_exec(
        'xdotool', 'search', '--name', escaped_title,
        stdout=asyncio.subprocess.PIPE,
    )
    yield from child.communicate()

    # Consider a closed terminal as focused (i.e. don't notify).
    return 0 == child.returncode


@asyncio.coroutine
def inhibit(window_title, summary, **_):
    if not window_title:
        return False

    is_window_focused = yield from is_focused(window_title)
    if is_window_focused:
        logger.info("Focused window %s inhibits %s.",
                    window_title, summary)
        return True
    exists = yield from window_exists(window_title)
    if exists:
        logger.info("Closed window %s inhibits %s.",
                    window_title, summary)
        return True

    return False


@asyncio.coroutine
def notify_send(
        summary, app_name=None, body=None, urgency='normal', icon=None,
        window_title=None, expire_time=None, hint=None,
        **_):

    inhibit_ = yield from inhibit(window_title, summary)
    if inhibit_:
        return

    args = [notify_send_path]
    if app_name:
        args.extend(['--app-name', app_name])
    if expire_time:
        args.extend(['--expire-time', str(expire_time)])
    if icon:
        args.extend(['--icon', icon])
    if urgency:
        args.extend(['--urgency', urgency])
    if hint:
        if not isinstance(hint, list):
            hint = [hint]
        for item in hint:
            args.extend(['--hint', item])

    args.append(summary)
    if body:
        args.append(body)

    logger.debug("Executing %s", ' '.join(args))
    child = yield from asyncio.create_subprocess_exec(*args)
    yield from child.communicate()
    logger.info("Notification sent: %r", summary)


class NotifyProtocol(asyncio.Protocol):
    def data_received(self, payload):
        logger.debug("<<< %r", payload)
        try:
            data = json.loads(payload.decode('utf-8'))
        except Exception as e:
            logger.warn("Failed to parse payload:\n%s", e)
            return

        asyncio.ensure_future(notify_send(**data))


DEBUG = os.environ.get('DEBUG')
logging.basicConfig(
    level=logging.DEBUG if DEBUG else logging.DEBUG,
    format='%(levelname).1s: %(message)s',
)
logger.info("Starting notify-proxy")

loop = asyncio.get_event_loop()
addr = os.environ.get('PROXY_ADDR', '127.0.0.1')
port = int(os.environ.get('PROXY_PORT', '1216'))
server = loop.run_until_complete(loop.create_server(
    NotifyProtocol, addr, port,
    reuse_address=True, reuse_port=True,
))

logger.info("Listening on %s:%d", addr, port)

if DEBUG:
    data = json.loads(DEBUG)
    logger.debug("Testing %r", data)
    loop.run_until_complete(asyncio.ensure_future(notify_send(**data)))
else:
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        logger.info('Done')

server.close()
loop.run_until_complete(server.wait_closed())
loop.close()
