---
- name: Install dependencies
  tags: notif,notify
  when: ansible_env.DESKTOP_SESSION is defined
  become: yes
  loop:
  - libnotify-bin
  - xdotool
  package: name={{ item }}

- name: Install notify-proxy script
  tags: notif,notify
  when: ansible_env.DESKTOP_SESSION is defined
  copy:
    src: ../notify-proxy
    dest: ~/.local/bin/notify-proxy
    mode: 0750

- name: Ensure .config/autostart
  tags: notif,notify
  file:
    state: directory
    dest: "~/.config/autostart/"

- name: Setup session autostart
  tags: notif,notify
  when: ansible_env.DESKTOP_SESSION is defined
  copy:
    src: ../notify-proxy.desktop
    dest: ~/.config/autostart/notify-proxy.desktop

- name: Install notify-client
  tags: notif,notify
  copy:
    src: ../notify-client
    dest: ~/.local/bin/notify-client
    mode: 0750

- name: Install notify.bash
  tags: notif,notify,bash
  copy:
    src: ../notify.bash
    dest: ~/.config/bashrc.d/notify.bash
    mode: 0750

- name: byobu directory
  tags: notif,notify,byobu
  file:
    state: directory
    path: ~/.config/byobu/

- name: .tmux.conf
  tags: notif,notify,byobu
  template:
    src: ../tmux.conf
    dest: ~/.config/byobu/.tmux.conf
