---
- name: Install dependencies
  when: ansible_env.DESKTOP_SESSION is defined
  become: yes
  package:
    name:
    - libnotify-bin
    - xdotool

- name: Directories
  loop:
  - ~/.config/autostart
  - ~/.config/byobu
  - ~/.local/bin
  file:
    state: directory
    path: "{{ item }}"

- name: Install scripts
  loop:
  - notify-client
  - notify-is-focused
  - notify-last-command
  copy:
    src: ../{{ item }}
    dest: ~/.local/bin/{{ item }}
    mode: 0750

- name: Install notify-proxy script
  when: ansible_env.DESKTOP_SESSION is defined
  copy:
    src: ../notify-proxy
    dest: ~/.local/bin/notify-proxy
    mode: 0750

- name: Setup session autostart
  when: ansible_env.DESKTOP_SESSION is defined
  copy:
    src: ../notify-proxy.desktop
    dest: ~/.config/autostart/notify-proxy.desktop

- name: .tmux.conf
  when: ansible_env.DESKTOP_SESSION is defined
  copy:
    src: ../tmux.conf
    dest: ~/.config/byobu/.tmux.conf
